### ISSUE TITLE
Broken as of 15 December

### ISSUE THREAD

**Issue by wsdt** [codebucks27/Nextjs-tailwindcss-blog-template#19]

**Comment by codebucks27** [comment]
Hey,

Since Contentlayer is no longer actively maintained, it causes issues with the dependencies. 

For now, I've replaced Contentlayer with [Velite.js](https://velite.js.org/) to handle the markdown files. Velite.js is quite similar to Contentlayer in terms of implementation, but there are a few changes you'll need to make. You can refer to the latest commit to compare the updates.

If you'd like to see the code from the YouTube tutorial, you can check the branch named [contentlayer](https://github.com/codebucks27/Nextjs-tailwindcss-blog-template/tree/Contentlayer).
